Repository esastack/esa-restclient, pull requests merged in 2021-06, with the labels that each got.

#84 docs(README.md): Modify the protocol version in QuickStart to HTTP1.1…
  README.md
  docs/Reference Doc/v0.1.0/quick_start/README.md
Labels: documentation

#86 use Unpooled#wrappedBuffer to reduce one memory copy
  httpclient-core/src/main/java/esa/httpclient/core/HttpRequestFacade.java
Labels: Optimization

#89 fix HttpUri#getParam
  httpclient-core/src/main/java/esa/httpclient/core/CompositeRequest.java
  httpclient-core/src/main/java/esa/httpclient/core/HttpRequestBaseImpl.java
  httpclient-core/src/main/java/esa/httpclient/core/HttpUri.java
  httpclient-core/src/main/java/esa/httpclient/core/exec/RedirectInterceptor.java
  httpclient-core/src/main/java/esa/httpclient/core/util/MultiValueMapUtils.java
  httpclient-core/src/test/java/esa/httpclient/core/HttpUriTest.java
  httpclient-core/src/test/java/esa/httpclient/core/util/MultiValueMapUtilsTest.java
Labels: bug

#93 add comment
  httpclient-core/src/main/java/esa/httpclient/core/netty/TimeoutHandle.java
Labels: Optimization
